package com.HiveSys.dashboard.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UploadLayout extends Panel {
	protected com.vaadin.ui.Upload boxUpload;
	protected com.vaadin.ui.TextField txtTitle;
	protected com.vaadin.ui.TextField txtFileType;
	protected com.vaadin.ui.TextField txtAuthor;
	protected com.vaadin.ui.DateField txtDateCreated;
	protected com.vaadin.ui.DateField txtDateModified;
	protected com.vaadin.ui.DateField txtDateUploaded;

	public UploadLayout() {
		Design.read(this);
	}
}
